/// get_keyname()
// This wasn't very fun to decode.
if (argument0 == ord("A")) return "A";
if (argument0 == ord("B")) return "B";
if (argument0 == ord("C")) return "C";
if (argument0 == ord("D")) return "D";
if (argument0 == ord("E")) return "E";
if (argument0 == ord("F")) return "F";
if (argument0 == ord("G")) return "G";
if (argument0 == ord("H")) return "H";
if (argument0 == ord("I")) return "I";
if (argument0 == ord("J")) return "J";
if (argument0 == ord("K")) return "K";
if (argument0 == ord("L")) return "L";
if (argument0 == ord("M")) return "M";
if (argument0 == ord("N")) return "N";
if (argument0 == ord("O")) return "O";
if (argument0 == ord("P")) return "P";
if (argument0 == ord("Q")) return "Q";
if (argument0 == ord("R")) return "R";
if (argument0 == ord("S")) return "S";
if (argument0 == ord("T")) return "T";
if (argument0 == ord("U")) return "U";
if (argument0 == ord("V")) return "V";
if (argument0 == ord("W")) return "W";
if (argument0 == ord("X")) return "X";
if (argument0 == ord("Y")) return "Y";
if (argument0 == ord("Z")) return "Z";
if (argument0 == ord("0")) return "0";
if (argument0 == ord("1")) return "1";
if (argument0 == ord("2")) return "2";
if (argument0 == ord("3")) return "3";
if (argument0 == ord("4")) return "4";
if (argument0 == ord("5")) return "5";
if (argument0 == ord("6")) return "6";
if (argument0 == ord("7")) return "7";
if (argument0 == ord("8")) return "8";
if (argument0 == ord("9")) return "9";
if (argument0 == vk_backspace) return "Backspace";
if (argument0 == vk_tab) return "Tab";
if (argument0 == vk_enter) return "Enter";
if (argument0 == vk_shift) return "Shift";
if (argument0 == vk_control) return "Control";
if (argument0 == vk_alt) return "Alt";
if (argument0 == vk_pause) return "Pause";
if (argument0 == 20/* CAPS LOCK */) return "CapsLock";
if (argument0 == vk_space) return "SpaceBar";
if (argument0 == vk_pageup) return "PageUp";
if (argument0 == vk_pagedown) return "PageDown";
if (argument0 == vk_end) return "End";
if (argument0 == vk_home) return "Home";
if (argument0 == vk_left) return "Left";
if (argument0 == vk_up) return "Up";
if (argument0 == vk_right) return "Right";
if (argument0 == vk_down) return "Down";
if (argument0 == vk_insert) return "Insert";
if (argument0 == vk_delete) return "Delete";
if (argument0 == vk_numpad0) return "NumPad 0";
if (argument0 == vk_numpad1) return "NumPad 1";
if (argument0 == vk_numpad2) return "NumPad 2";
if (argument0 == vk_numpad3) return "NumPad 3";
if (argument0 == vk_numpad4) return "NumPad 4";
if (argument0 == vk_numpad5) return "NumPad 5";
if (argument0 == vk_numpad6) return "NumPad 6";
if (argument0 == vk_numpad7) return "NumPad 7";
if (argument0 == vk_numpad8) return "NumPad 8";
if (argument0 == vk_numpad9) return "NumPad 9";
if (argument0 == vk_multiply) return "NumPad *";
if (argument0 == vk_add) return "NumPad +";
if (argument0 == vk_subtract) return "NumPad -";
if (argument0 == vk_decimal) return "NumPad .";
if (argument0 == vk_divide) return "NumPad /";
if (argument0 == vk_lcontrol) return "Control";
if (argument0 == vk_lshift) return "Shift";
return string(argument0);
